import path from "path";
import { syncEnvironmentVariables } from "/Users/jeff/Projects/sysadmin/scripts/shared-env-sync.mts";

// Configuration
const APP_UUID = "a840k0wg0w8g88swcs480w8w"; // Cards Production UUID
const TARGET_FILE = path.join(process.cwd(), ".env.local");

// Validation Lists
const CRITICAL_VARS = ["DATABASE_URL", "AUTH_SECRET"];

const KNOWN_VARS = [
  "AUTH_GOOGLE_ID",
  "AUTH_GOOGLE_SECRET",
  "AUTH_APPLE_ID",
  "AUTH_APPLE_SECRET",
  "AUTH_GITHUB_ID",
  "AUTH_GITHUB_SECRET",
  "EMAIL_SERVER",
  "EMAIL_FROM",
  "MAIL_API_KEY",
  "CF_ACCESS_CLIENT_ID",
  "CF_ACCESS_CLIENT_SECRET",
];

const LEGACY_VARS = [
  "CLERK_SECRET_KEY",
  "ENABLE_MOCK_PLAID",
  "GEMINI_API_KEY",
  "LOGODEV_SECRET_KEY",
  "LOGO_DEV_TOKEN",
  "NEXT_PUBLIC_LOGODEV_PUBLISHABLE_KEY",
  "NEXT_PUBLIC_APP_NAME",
  "NEXT_PUBLIC_APP_URL",
  "NEXT_PUBLIC_NOVU_APPLICATION_ID",
  "NOVU_API_KEY",
  "NEXT_PUBLIC_POSTHOG_HOST",
  "NEXT_PUBLIC_POSTHOG_KEY",
  "NEXT_PUBLIC_SENTRY_DSN",
  "SENTRY_ORG",
  "SENTRY_PROJECT",
  "NEXT_PUBLIC_STRIPE_BUTTON_ID",
  "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY",
  "STRIPE_SECRET_KEY",
  "STRIPE_WEBHOOK_SECRET",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "NEXT_PUBLIC_SUPABASE_URL",
  "SUPABASE_SERVICE_ROLE_KEY",
  "PLAID_CLIENT_ID",
  "PLAID_SECRET",
  "PLAID_ENV",
  "POSTGRES_URL_NON_POOLING",
  "DIRECT_URL",
  "RESEND_API_KEY",
  "UPSTASH_REDIS_REST_TOKEN",
  "UPSTASH_REDIS_REST_URL",
  "TEST_CLIENT_ENGINE_REMOTE_EXECUTOR",
  "_CLUSTER_NETWORK_NAME_",
];

// Execute Shared Service
syncEnvironmentVariables({
  appName: "Cards",
  appUuid: APP_UUID,
  targetFile: TARGET_FILE,
  criticalVars: CRITICAL_VARS,
  knownVars: KNOWN_VARS,
  scanIgnorePatterns: LEGACY_VARS,
});
