// Re-export useful Drizzle utilities (Safe for client)
export {
  sql,
  eq,
  and,
  or,
  not,
  gt,
  gte,
  lt,
  lte,
  ne,
  isNull,
  isNotNull,
  inArray,
  notInArray,
  between,
  like,
  ilike,
  asc,
  desc,
  relations,
  count,
} from "drizzle-orm";
export {
  pgTable,
  pgSchema,
  text,
  integer,
  boolean,
  timestamp,
  decimal,
  uuid,
  varchar,
  serial,
  bigint,
  real,
  doublePrecision,
  date,
  time,
  json,
  jsonb,
  index,
  unique,
  uniqueIndex,
  pgEnum,
  primaryKey,
} from "drizzle-orm/pg-core";

// Re-export public schema (shared auth tables with RLS) - Safe for client (types and schema definitions)
export * as publicSchema from "./public-schema";
export type {
  User,
  NewUser,
  OAuthAccount,
  NewOAuthAccount,
  Session,
  NewSession,
  VerificationToken,
  NewVerificationToken,
  UserPreferences,
  NewUserPreferences,
} from "./public-schema";
